name: benchmark

on:
  push:
    branches:
      - main

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: build benchmark against clang
        run: |
            clang --version
            sudo apt-get install libc++-dev
            make clang_benchmark_build

      - name: build benchmark against gcc
        run: |
            gcc --version
            make gcc_benchmark_build

      - name: benchmark against clang
        run: |
            clang --version
            make clang_benchmark_run

      - name: benchmark against gcc
        run: |
            gcc --version
            make gcc_benchmark_run
