name: benchmark

on:
  push:
    branches:
      - main
      - hashtable

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install dependencies
        run: |
            pip3 install conan
            conan profile detect
            mkdir build && cd build
            conan install .. --build=missing
            cd ..

      - name: benchmark
        run: |
            make benchmark
