name: benchmark

on:
  push:
    branches:
      - main

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: benchmark
        run: |
            make benchmark
