name: portable_validity

on:
  push: {}

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: generate files
        run: ./portable_header_process.sh portable_headers_new

      - name: diff
        run: diff -r portable_headers portable_headers_new
