name: unit_test

on:
  push: {}

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: submodule
        run: git submodule update --init --recursive

      - name: build test against clang
        run: |
            clang --version
            sudo bash llvm.sh 20
            sudo cp /usr/bin/clang-20 /usr/bin/clang
            sudo cp /usr/bin/clang++-20 /usr/bin/clang++
            clang --version

            # make clang_test_build

      - name: build test against gcc
        run: |
            gcc --version
            make gcc_test_build

      - name: test against clang
        run: |
            clang --version
            # make clang_test_run

      - name: test against gcc
        run: |
            gcc --version
            make gcc_test_run
