name: unit_test

on:
  push: {}

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: submodule
        run: git submodule update --init --recursive

      - name: install valgrind and unbuffer
        run: sudo apt install -y valgrind expect

      - name: test
        run: make test
